### ISSUE TITLE
Custom Plugin Support

### ISSUE THREAD

**Issue by Byteingpython** [flytegg/plugin-portal#12]
It would be cool, if it was possible to add custom Plugins that are released privately on github.
Maybe this would be possible via a github token

**Comment by ZwergTuete** [comment]
Hey, this is a very good idea! I'll work on it 👍

**Comment by Dawsson** [comment]
Hey, I apologize for the late response but this is already made inside of Plugin Portal Premium using our adapter system

@ZwergTuete

**Comment by ZwergTuete** [comment]
Ohh yeah, np
