### ISSUE TITLE
is this project abandoned?

### ISSUE THREAD

**Issue by qtqgyt** [flytegg/plugin-portal#17]

**Comment by Dawsson** [comment]
Lmao it has been pretty inactive but I am coding the backend for plugin portal atm. Hopefully I should start making some progress on the plugin itself soon

TLDR; nope

**Comment by gamer50082** [comment]
discord invite is broken and the website isnt online so no /discord either

**Comment by Dawsson** [comment]
not abandoned, just put on back log behind other projects. for the website: @joshbker @stephendotgg any thoughts?

**Comment by gamer50082** [comment]
how about the discord invite the spigot page on isnt working

**Comment by stephendotgg** [comment]
> how about the discord invite the spigot page on isnt working

https://discord.gg/vVNQSUSsMv

**Comment by qtqgyt** [comment]
ok
