### ISSUE TITLE
No Malware detection

### ISSUE THREAD

**Issue by c4vxl** [flytegg/plugin-portal#18]
You mentioned, "Malware Detection: When installing a plugin, you don't need to be afraid if it has malware! We'll handle this for you instead." I noticed that there is no malware detection in place. So please correct your plugin pages!

Best regards,
**c4vxl**

**Comment by Dawsson** [comment]
Handled on backend, nothing on client side at this moment. We will incorporate malware detection for unsupported plugins soon.

**Comment by stephendotgg** [comment]
Hi there,

You emailed us about the same issue. PP has many safeguards in place, one of them is our **own malware detection which we run behind the scenes** and so you aren't going to find it in the decompiled code. It would be inefficient to scan on download and have the client deal with the load of that, considering we have an index of all the downloadable jars.

As I'm sure your concerned about the safety of others, I'll share some of our other safeguards which should give you peace of mind:

1. We prevent users from accidentally clicking on a separate website. This is a huge issue which inexperienced users commonly encounter.
2. The platforms which we support are scanned for malware at a mass scale.
3. We also use a custom scanner when needed, on top of looking through code at our most downloaded plugins.

Closing as answered. You can rest easy now!
