### ISSUE TITLE
What is the licence of this code?

### ISSUE THREAD

**Issue by woliver99** [flytegg/plugin-portal#22]
I would like to know if it's an MIT license or an Apache license before I start making pull requests for this plugin.

**Comment by Dawsson** [comment]
i'll get in contact with the other owner and see. If you do decide to make a PR, please make a PR to the 2.0.0 branch. will let you know soon!

**Comment by Dawsson** [comment]
@woliver99 We are planning on going with MIT atm, will let you know of any changes

**Comment by woliver99** [comment]
Oh perfect thank you!
