### ISSUE TITLE
Plugin Error, No Way to connect with the developer or support, Not enough plugin information.

### ISSUE THREAD

**Issue by OPADILOP** [flytegg/plugin-portal#23]

**Comment by Dawsson** [comment]
Our discord has full support, @joshbker @stephendotgg Any updates on the fixed discord link?

**Comment by Dawsson** [comment]
Here's a link to our discord: https://discord.gg/Za7mkD3AFZ

**Comment by stephendotgg** [comment]
Discord link updated on both marketplaces
