### ISSUE TITLE
Command prompt from clicking plugin in /pp list should reference specific plugin

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/plugin-portal#46]
In /pp list, the click to view this plugin opens the multiple plugins found menu. Because it's already installed and they are trying to view the specific plugin they downloaded, we should direct them straight to that /pp view:

![image](https://github.com/flytegg/plugin-portal/assets/138625055/daf6f9c3-de52-4f2b-9b3d-5944e9efee6b)

**Comment by MLGPenguin** [comment]
now prompts `/pp view hXiIvTyT MODRINTH -byId` (for essentials)
