### ISSUE TITLE
Should not be able to run /pp delete PluginPortal

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/plugin-portal#47]
Seems to be a duplicate issue here, but ignoring that, /pp delete PluginPortal should not show the option to delete PluginPortal, especially since we do not support this. /pp delete --platformId 5qkQnnWO prompted from the multiple options found menu just returns saying no plugin file found (As it should).

![image](https://github.com/flytegg/plugin-portal/assets/138625055/fa22a06f-e623-4dc5-b5f8-1d9da0fda5bd)

**Comment by stephendotgg** [comment]
I suspect this may actually work as intended without this dupe issue. However, this could still not be closed because if one was to type "/pp delete Plug" to delete PlugManX or something, they'd still find PP in their list.

**Comment by MLGPenguin** [comment]
now responds with `you cannot delete plugin portal` on all attempts to delete plugin portal
