### ISSUE TITLE
/pp install tab complete does not include quotes around plugin names leading to wrong installation

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/plugin-portal#51]
In /pp install tab complete, it doesnt put speech marks around it. So when I run this, it obviously shows the second menu, where it only reads the WolrdEdit part. This basically means that anything that anyone tab completes from /pp install which contains a space they will have to manually add the speech marks and if they don't then they will either accidently isntall something else or be showed the dupe menu for something different.

![image](https://github.com/flytegg/plugin-portal/assets/138625055/4f13546e-e80c-4be2-89e9-e7f1f74ac15e)
![image](https://github.com/flytegg/plugin-portal/assets/138625055/59b8be2f-bf75-415c-8d46-27a119580543)

**Comment by MLGPenguin** [comment]
Fixed in latest snapshot
