### ISSUE TITLE
/pp view triggers infinite loop in multi plugin menu

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/plugin-portal#52]
I did /pp view test. It brought up the multiple plugin menu. When clicking any of those, it prompts the command you see in that chatbar. The obvious problem there is that these are all named test and on Spigot, so it brings up this menu again. Basically a constant loop. Is this where the platform ID would be relevant? Even if so, we're going to have to make the menu more usable from this perspective, becaues as a user I'm currently stuck in a loop trying to view any of these plugins

![image](https://github.com/flytegg/plugin-portal/assets/138625055/97a3254b-3e98-4a95-88b3-15b9190baa71)

**Comment by MLGPenguin** [comment]
Clicking in this menu now yields `/pp view "97218" SPIGOTMC -byId`
