### ISSUE TITLE
Resource page URL in /pp view

### ISSUE THREAD

**Issue by stephendotgg** [flytegg/plugin-portal#53]
Have another option in view next to action buttons in /pp view to open the resource page URL. I know we're very much an in-game package manager, but me personally I'd like peace of mind sometimes and probably would find myself opening the resource page.

![image](https://github.com/flytegg/plugin-portal/assets/138625055/c58bafaa-ff04-4a6f-adb8-2f49d4a09757)

**Comment by Dawsson** [comment]
@stephendotgg Would you prefer the ability to click on the title to open the page or a button next to Install?

**Comment by stephendotgg** [comment]
@Dawsson Gonna sound wild but we could do both?

**Comment by Dawsson** [comment]
> @Dawsson Gonna sound wild but we could do both?

Thats fine with me, ill get started on that.

**Comment by Dawsson** [comment]
Added to title, button can come once we revamp the buttons at the bottom
