### ISSUE TITLE
Can't install from spigot for some reason

### ISSUE THREAD

**Issue by BurkenDev** [flytegg/plugin-portal#54]
Can't even isntall LuckPerms on a fresh server using version 2.0.0 on latest paper 1.21.

This is what happens.

![image](https://github.com/flytegg/plugin-portal/assets/72360068/b1019474-b4fb-4fc2-a6ee-051b78bf22c4)

Even /pp install LuckPerms do not work.
/pp view does work but no go on the install button there.

I guess you can't bypass the cloudflare detection for spigot, which you shouldn't even.

**Comment by Dawsson** [comment]
Problem solved, thank you for the issue. Fixed in version 2.0.2 https://modrinth.com/plugin/pluginportal/version/2.0.2

![image](https://github.com/flytegg/plugin-portal/assets/88049488/5e33dbcf-ec9b-4d12-88bd-e983353a15f2)
