### ISSUE TITLE
Manage Plugin with space in the name

### ISSUE THREAD

**Issue by Olthoo** [flytegg/plugin-portal#58]
Currently the auto fill will fill plugin with space in the name, that interfer with source selector

![image](https://github.com/flytegg/plugin-portal/assets/86952294/2ab6db8c-e113-44fc-87bc-c7af81498aa1)
![image](https://github.com/flytegg/plugin-portal/assets/86952294/5d55729a-d440-4f84-a339-7250c836f9f9)

A simple fix would be to replace the space with an underscore in the autofill

**Comment by Dawsson** [comment]
@MLGPenguin was working on a fix for this. Penguin, any updates?

**Comment by Dawsson** [comment]
Same as #51

**Comment by MLGPenguin** [comment]
FIxed in latest snapshot
