### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by Craftefix** [flytegg/plugin-portal#60]
### Feature Description

Check for version on join of op's or ppl who have the pp.version perm, or manually with `/pp version`

### Why is this feature needed?

Version not noticeable without filemanager

**Comment by Dawsson** [comment]
You can view the version of a plugin using `/help <pluginName>`, though its not a bad idea.

Do you want to see the version of plugin portal, another plugin, or both?

**Comment by Olthoo** [comment]
you can use the paper command /version {plugin}

**Comment by Dawsson** [comment]
Closing due to /version
