### ISSUE TITLE
[Bug]: invalid discord link

### ISSUE THREAD

**Issue by synuhaan** [flytegg/plugin-portal#76]
### Description

I get a invalid invitation message when i click the discord link: https://discord.com/invite/flyte
![image](https://github.com/user-attachments/assets/826f8d3c-d871-42bc-b3c1-99ffbdcc65ed)
(sorry for the dutch text)

### Minimal Reproduction

open the given link https://discord.com/invite/flyte

### Dump

nvt

**Comment by Dawsson** [comment]
Thanks for letting us know, ill see what I can do

https://discord.gg/d9sAesbx
