### ISSUE TITLE
Extra plugin information in pp view

### ISSUE THREAD

**Issue by Davidbudr** [flytegg/plugin-portal#79]
### Feature Description

plugin ID and a link clickable from console to view download page,
either on pp view by default or obfuscated by a -verbose tag for pp view

### Why is this feature needed?

Ease of use.
Allows for downloading and updating plugins for servers directly from console without the need to search for ID when multiple items are returned in pp view/install.

### Additional Info

Example:
![pp verbose](https://github.com/user-attachments/assets/a0f5d28f-8c2d-4a9f-b5ff-4974e9ca1849)

**Comment by MLGPenguin** [comment]
I don't know if it's possible to put clickable links in console but I have added IDs to the console as suggested for the next release.
